# This workflow automatically publishes the package to NPM and GHCR when a new release is created.
# Before, creating a new release, make sure to update the package version in package.json
# and add a Granular Access Token (with read and write packages scope)
# to the repository secrets with the name NPM_TOKEN.
# Once, the release has been published remove it from the repository secrets.

name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: npm
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-ghcr:
    runs-on: ubuntu-latest
    name: Docker
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
         docker build . --tag ghcr.io/${{ github.actor }}/tldr-lint:latest
         docker push ghcr.io/${{ github.actor }}/tldr-lint:latest
